[package]
name = "app"
version = "0.1.0"
authors = ["weichiao-cs07 <erica.cs70g@nctu.edu.tw>"]

[dependencies]
sha3 = "0.8.2"
sha2 = "0.7.1"
ring = "0.16.6"
chrono = "0.4.9"
secp256k1 = {version = "0.15.5", features = [ "recovery"]}
rand = "0.6.5"
hex = "0.4.0"
